//Converting Strings to Numbers
// console.log(5+"5")
// console.log(Number("5"))
// console.log(Number(" ssri"))
// Converting Numbers to Strings

// console.log(String(5+5))
// console.log(String(5.5))

// Converting Booleans to Numbers


// console.log(Number(false))
// console.log(Number(true))
//Conversions done by + operator

// console.log(5+"5") // 55
// console.log(5-"5") // 0
// console.log(5+null) // 5
// console.log(5-null)//5  
// console.log(5+ undefined) // naa
// console.log("5" * "10")//50



